class ShoppingAgent:
    """
    Represents an AI shopping agent.

    The ShoppingAgent can communicate with other agents,
    but its messages will eventually pass through
    Sentinel-A2A before reaching them.
    """

    def __init__(self):
        # Name used to identify this agent.
        self.name = "ShoppingAgent"

        # Tools that this agent is allowed to request.
        #
        # Sentinel-A2A will use these permissions to
        # prevent the agent from accessing unauthorized tools.
        self.allowed_tools = [
            "search_product",
            "create_payment"
        ]

    def create_request(self, message, tool=None):
        """
        Create a request that can be sent to another agent.

        Parameters:
            message:
                Instruction/message generated by the agent.

            tool:
                Optional tool that the agent wants to use.

        Returns:
            A dictionary representing the agent's request.
        """

        return {
            "source_agent": self.name,
            "message": message,
            "tool": tool,
            "allowed_tools": self.allowed_tools
        } 